<?xml version="1.0" encoding="UTF-8"?>

<project
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.bfabric</groupId>
    <artifactId>bfabric</artifactId>
    <version>13</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>application</artifactId>
  <version>13.0.0-SNAPSHOT</version>
  <name>B-Fabric Application</name>
  <description>B-Fabric with its underlying data management system, JSF-based GUI, and SOAP-based Web services.</description>
  <url>https://bfabric.org/</url>
  <packaging>war</packaging>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <db.driver>org.postgresql.Driver</db.driver>
    <db.url>jdbc:postgresql://localhost:5432/bfabric_test</db.url>
    <db.username>bfabric</db.username>
    <db.password>changeit</db.password>
    <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZ</maven.build.timestamp.format>
    <maven.build.timestamp.timezone>Europe/Zurich</maven.build.timestamp.timezone>
    <root.basedir>${basedir}/..</root.basedir>
    <version>${project.version}</version>
    <apache.fop.version>2.11</apache.fop.version>
    <apache.poi.version>5.5.1</apache.poi.version>
    <arquillian.version>1.10.0.Final</arquillian.version>
    <commons.beanutils.version>1.11.0</commons.beanutils.version>
    <commons.text.version>1.15.0</commons.text.version>
    <font-awesome.version>7.1.0</font-awesome.version>
    <freemarker.version>2.3.34</freemarker.version>
    <google.jimfs.version>1.3.1</google.jimfs.version>
    <gson.version>2.13.2</gson.version>
    <hibernate.version>5.6.15.Final</hibernate.version>
    <htmlparser.version>2.1</htmlparser.version>
    <ical4j.version>4.0.0-alpha12</ical4j.version><!-- beta requires code migration -->
    <jakarta.version>8.0.0</jakarta.version>
    <junit.version>4.13.2.redhat-00001</junit.version>
    <junit.jupiter.version>5.14.2</junit.jupiter.version>
    <librepdf.version>1.4.2</librepdf.version>
    <log4j.version>2.21.1</log4j.version>
    <lucene.version>8.11.4</lucene.version><!-- Lucene 9.0 requires JDK 11 or newer -->
    <properties-maven-plugin.version>1.2.1</properties-maven-plugin.version>
    <omnifaces.version>3.14.12</omnifaces.version>
    <owasp.sanitizer.version>20240325.1.0.redhat-00001</owasp.sanitizer.version>
    <pdfbox.version>3.0.6</pdfbox.version>
    <primefaces.version>13.0.10</primefaces.version><!-- PF 14 requires JDK 11 or newer -->
    <primefacesextensions.version>13.0.13</primefacesextensions.version>
    <qrcodegen.version>1.8.0</qrcodegen.version>
    <reflections.version>0.10.2.redhat-00001</reflections.version>
    <samaxes.maven.version>1.7.6</samaxes.maven.version>
    <slf4j.version>2.1.0-alpha1</slf4j.version>
    <spotbugs.version>4.9.8</spotbugs.version>
    <spring.security.version>5.8.16</spring.security.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>${jakarta.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-core</artifactId>
      <version>${spring.security.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-context</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-expression</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.springframework</groupId>
          <artifactId>spring-beans</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-core</artifactId>
      <version>${hibernate.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.glassfish.jaxb</groupId>
          <artifactId>jaxb-runtime</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.activation</groupId>
          <artifactId>javax.activation-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.xml.bind</groupId>
          <artifactId>jaxb-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-ehcache</artifactId>
      <version>${hibernate.version}</version>
    </dependency>
    <dependency>
      <groupId>org.primefaces</groupId>
      <artifactId>primefaces</artifactId>
      <version>${primefaces.version}</version>
    </dependency>
    <dependency>
      <groupId>org.primefaces.extensions</groupId>
      <artifactId>primefaces-extensions</artifactId>
      <version>${primefacesextensions.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.primefaces</groupId>
          <artifactId>primefaces</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- Note: Remove this dependency when we have migrated all systems to Payara Version >= 2022.1! -->
    <dependency>
      <groupId>org.primefaces.extensions</groupId>
      <artifactId>resources-monacoeditor</artifactId>
      <version>${primefacesextensions.version}</version>
    </dependency>
    <dependency>
      <groupId>org.omnifaces</groupId>
      <artifactId>omnifaces</artifactId>
      <version>${omnifaces.version}</version>
    </dependency>
    <!-- Data Exporter -->
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>${apache.poi.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>${apache.poi.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.librepdf</groupId>
      <artifactId>openpdf</artifactId>
      <version>${librepdf.version}</version>
    </dependency>
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>font-awesome</artifactId>
      <version>${font-awesome.version}</version>
    </dependency>
    <!--Required to get rid of the following message: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-nop</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>${log4j.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
      <version>${log4j.version}</version>
    </dependency>
    <!-- Sanitizer required for text editor to prevent xss attacks! -->
    <dependency>
      <groupId>com.googlecode.owasp-java-html-sanitizer</groupId>
      <artifactId>owasp-java-html-sanitizer</artifactId>
      <version>${owasp.sanitizer.version}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit.jupiter.version}</version>
      <scope>test</scope>
    </dependency>
    <!-- Working with PDF documents -->
    <dependency>
      <groupId>org.apache.pdfbox</groupId>
      <artifactId>pdfbox</artifactId>
      <version>${pdfbox.version}</version>
    </dependency>
    <!-- FOP: Formatting Objects Processor: needed for PDF generation! -->
    <dependency>
      <groupId>org.apache.xmlgraphics</groupId>
      <artifactId>fop</artifactId>
      <version>${apache.fop.version}</version>
    </dependency>
    <!-- High-level syntactical analyzer: needed for HTML to text transformation! -->
    <dependency>
      <groupId>org.htmlparser</groupId>
      <artifactId>htmlparser</artifactId>
      <version>${htmlparser.version}</version>
      <type>jar</type>
      <scope>compile</scope>
    </dependency>
    <!-- Utility for the classes that are in java.text hierarchy -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-text</artifactId>
      <version>${commons.text.version}</version>
    </dependency>
    <!-- Bean property utils -->
    <dependency>
      <groupId>commons-beanutils</groupId>
      <artifactId>commons-beanutils</artifactId>
      <version>${commons.beanutils.version}</version><!--$NO-MVN-MAN-VER$ -->
    </dependency>
    <!-- Runtime metadata analysis -->
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>${reflections.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-core</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-queryparser</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <!-- In-memory implementation of Java's java.nio.file abstract file system API. -->
    <dependency>
      <groupId>com.google.jimfs</groupId>
      <artifactId>jimfs</artifactId>
      <version>${google.jimfs.version}</version>
      <scope>compile</scope>
    </dependency>
    <!-- Mail template engine: https://mvnrepository.com/artifact/org.freemarker/freemarker -->
    <dependency>
      <groupId>org.freemarker</groupId>
      <artifactId>freemarker</artifactId>
      <version>${freemarker.version}</version>
    </dependency>
    <!-- Convert Java Objects into their JSON representation -->
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>${gson.version}</version>
    </dependency>
    <!-- calendar parser and object model -->
    <dependency>
      <groupId>org.mnode.ical4j</groupId>
      <artifactId>ical4j</artifactId>
      <version>${ical4j.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.sun.mail</groupId>
          <artifactId>javax.mail</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.activation</groupId>
          <artifactId>javax.activation-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- QR code generator -->
    <dependency>
      <groupId>io.nayuki</groupId>
      <artifactId>qrcodegen</artifactId>
      <version>${qrcodegen.version}</version>
    </dependency>
    <!-- Arquillian JUnit testing -->
    <dependency>
      <groupId>org.jboss.arquillian</groupId>
      <artifactId>arquillian-bom</artifactId>
      <version>${arquillian.version}</version>
      <scope>test</scope>
      <type>pom</type>
    </dependency>
    <dependency>
      <groupId>org.jboss.arquillian.junit</groupId>
      <artifactId>arquillian-junit-container</artifactId>
      <version>${arquillian.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
      <version>${spotbugs.version}</version>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>jboss.releases</id>
      <name>JBoss Enterprise Maven Repository</name>
      <url>https://maven.repository.redhat.com/ga/</url>
    </repository>
  </repositories>

  <build>
    <finalName>${project.parent.artifactId}-${project.version}</finalName>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
      <plugin>
        <!-- Create a B-Fabric jar file by using the following maven command: "mvn clean compile assembly:single" -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>${maven-assembly-plugin.version}</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>fully.qualified.MainClass</mainClass>
            </manifest>
          </archive>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>sql-maven-plugin</artifactId>
        <configuration>
          <driver>${db.driver}</driver>
          <url>${db.url}</url>
          <username>${db.username}</username>
          <password>${db.password}</password>
          <skip>false</skip>
          <autocommit>true</autocommit>
          <onError>continue</onError>
        </configuration>
        <executions>
          <execution>
            <id>update-db-build-info</id>
            <phase>process-resources</phase>
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <autocommit>true</autocommit>
              <sqlCommand>
                UPDATE systemproperty
                SET value=('${maven.build.timestamp}'::TIMESTAMP AT TIME ZONE 'UTC') AT TIME ZONE 'Europe/Zurich'
                WHERE name = 'deploymentCompilationDateTime';
                UPDATE systemproperty
                SET value='${buildNumber}'
                WHERE name = 'deploymentGitRevisionId';
                UPDATE systemproperty
                SET value='${scmBranch}'
                WHERE name = 'deploymentBranchName';
              </sqlCommand>
              <skipOnConnectionError>true</skipOnConnectionError>
              <onError>continue</onError>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>properties-maven-plugin</artifactId>
        <version>${properties-maven-plugin.version}</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>write-project-properties</goal>
            </goals>
            <configuration>
              <outputFile>${project.build.outputDirectory}/pom.properties</outputFile>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
        <version>3.2.1</version>
        <executions>
          <execution>
            <phase>validate</phase>
            <goals>
              <goal>create</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <doCheck>false</doCheck>
          <doUpdate>false</doUpdate>
          <shortRevisionLength>8</shortRevisionLength>
          <timestampFormat>yyyy-MM-dd'T'HH:mm:ssZ</timestampFormat>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>m2e</id>
      <activation>
        <property>
          <name>m2e.version</name>
        </property>
      </activation>
    </profile>
    <profile>
      <id>arq-payara-remote</id>
      <properties>
        <skipTests>false</skipTests>
      </properties>
      <dependencies>
        <dependency>
          <groupId>fish.payara.arquillian</groupId>
          <artifactId>arquillian-payara-server-remote</artifactId>
          <version>3.1</version>
          <scope>test</scope>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.5.4</version>
            <configuration>
              <!-- This needs tuning -->
              <systemPropertyVariables>
                <arquillian.launch>glassfish-remote</arquillian.launch>
              </systemPropertyVariables>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
