/*
    MIT License

    Copyright (c) 2005-2026 Functional Genomics Center Zurich, UZH/ETH Zurich

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
 */

package org.bfabric.webservice.client.endpoint;

import org.bfabric.Messages;
import org.bfabric.enums.WorkunitStatusEnum;
import org.bfabric.util.CollectionHelper;
import org.bfabric.util.StringHelper;
import org.bfabric.webservice.client.exception.SoapClientException;
import org.bfabric.webservice.request.parameter.XMLRequestParameterSaveWorkunit;
import org.bfabric.xml.entity.XMLWorkunit;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class EPWorkunitIT extends AbstractIT {

    public XMLWorkunit createWorkunit() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setName(S5);
        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);
        xmlRequestSaveWorkunit.setStatus(WorkunitStatusEnum.PENDING.toString());
        xmlRequestSaveWorkunit.setDescription(S5);

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        if (workunit.getErrorreport() != null) {
            throw new SoapClientException("Could not create workunit: " + workunit.getErrorreport());
        }

        return workunit;
    }

    public void deleteWorkunit(Long id) {
        getSoapClient().getEpWorkunit().getWmDelete().delete(id);
    }

    @Test
    public void workunitShouldBeCreated() {
        XMLWorkunit workunit = createWorkunit();

        Assertions.assertNull(workunit.getErrorreport());

        Assertions.assertEquals(S5, workunit.getName());
        Assertions.assertEquals(Long.valueOf(CONTAINER_ID), workunit.getContainer().getId());
        Assertions.assertEquals(Long.valueOf(APPLICATION_ID), workunit.getApplication().getId());
        Assertions.assertEquals(WorkunitStatusEnum.PENDING.toString(), workunit.getStatus());
        Assertions.assertEquals(S5, workunit.getDescription());

        deleteWorkunit(workunit.getId());
    }

    @Test
    public void workunitShouldBeCreatedWithAutoGeneratedName() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNull(workunit.getErrorreport());
        Assertions.assertNotNull(workunit.getId());
        Assertions.assertNotNull(workunit.getName());
    }

    @Test
    public void workunitShouldBeDeleted() {
        XMLWorkunit workunit = createWorkunit();

        XMLWorkunit deletedWorkunit = getSoapClient().getEpWorkunit().getWmDelete().delete(workunit.getId());

        Assertions.assertNull(deletedWorkunit.getErrorreport());
        Assertions.assertNull(deletedWorkunit.getId());
    }

    @Test
    public void workunitShouldBeRead() {
        XMLWorkunit workunit = createWorkunit();

        XMLWorkunit readWorkunit = getSoapClient().getEpWorkunit().getWmRead().getEntity(workunit.getId());
        XMLWorkunit readWorkunitDuplicate = getSoapClient().getEpWorkunit().getWmRead().getEntity(workunit.getId());

        Assertions.assertNotNull(readWorkunit);
        Assertions.assertNotNull(readWorkunitDuplicate);

        Assertions.assertSame(readWorkunit, readWorkunitDuplicate);

        Assertions.assertNull(readWorkunit.getErrorreport());

        Assertions.assertEquals(S5, readWorkunit.getName());
        Assertions.assertEquals(Long.valueOf(CONTAINER_ID), readWorkunit.getContainer().getId());
        Assertions.assertEquals(Long.valueOf(APPLICATION_ID), readWorkunit.getApplication().getId());
        Assertions.assertEquals(WorkunitStatusEnum.PENDING.toString(), readWorkunit.getStatus());
        Assertions.assertEquals(S5, readWorkunit.getDescription());

        deleteWorkunit(readWorkunit.getId());
    }

    @Test
    public void workunitShouldBeUpdated() {
        XMLWorkunit workunit = createWorkunit();

        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setId(workunit.getId());

        xmlRequestSaveWorkunit.setName(StringHelper.generateString(6));
        String UPDATEDAPPLICATION_ID = "2";
        xmlRequestSaveWorkunit.setApplicationid(UPDATEDAPPLICATION_ID);
        xmlRequestSaveWorkunit.setDescription(StringHelper.generateString(6));

        XMLWorkunit updatedWorkunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNull(updatedWorkunit.getErrorreport());

        Assertions.assertEquals(StringHelper.generateString(6), updatedWorkunit.getName());
        Assertions.assertEquals(Long.valueOf(UPDATEDAPPLICATION_ID), updatedWorkunit.getApplication().getId());
        Assertions.assertEquals(StringHelper.generateString(6), updatedWorkunit.getDescription());

        deleteWorkunit(workunit.getId());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToInvalidStatus() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setName(S5);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);
        xmlRequestSaveWorkunit.setStatus(WorkunitStatusEnum.INVALID.toString());

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);
        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getStatus());
        Assertions.assertEquals("Invalid status: " + WorkunitStatusEnum.INVALID + ". Valid values: " + CollectionHelper.print(WorkunitStatusEnum.getValidEnumValues()) + "!", workunit
            .getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonExistingApplication() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setName(S5);
        xmlRequestSaveWorkunit.setApplicationid(getEntityIdNonExistingAsString());

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getApplication());
        Assertions.assertEquals("There is no application with id " + getEntityIdNonExistingAsString() + "!", workunit.getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonExistingContainer() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(getEntityIdNonExistingAsString());

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getContainer());
        Assertions.assertEquals("There is no container with id " + getEntityIdNonExistingAsString() + "!", workunit.getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonExistingDataset() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setName(S5);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);
        xmlRequestSaveWorkunit.setDatasetid(getEntityIdNonExistingAsString());

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getDataset());
        Assertions.assertEquals("There is no dataset with id " + getEntityIdNonExistingAsString() + "!", workunit.getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonExistingInputDataset() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setName(S5);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);
        xmlRequestSaveWorkunit.setInputdatasetid(getEntityIdNonExistingAsString());

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getInputdataset());
        Assertions.assertEquals("There is no dataset with id " + getEntityIdNonExistingAsString() + "!", workunit.getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonSpecifiedApplication() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setName(S5);

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getApplication());
        Assertions.assertEquals(Messages.get("applicationRequired"), workunit.getErrorreport());
    }

    @Test
    public void workunitShouldNotBeCreatedDueToNonSpecifiedContainer() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getContainer());
        Assertions.assertTrue(workunit.getErrorreport().equals("parentId must not be null") || workunit.getErrorreport().equals("parentClassName must not be null") || workunit.getErrorreport()
            .equals("container must not be null"));
    }

    @Test
    public void workunitShouldNotBeCreatedDueToTooLongName() {
        XMLRequestParameterSaveWorkunit xmlRequestSaveWorkunit = new XMLRequestParameterSaveWorkunit();

        xmlRequestSaveWorkunit.setContainerid(CONTAINER_ID);
        xmlRequestSaveWorkunit.setApplicationid(APPLICATION_ID);
        xmlRequestSaveWorkunit.setName(StringHelper.generateString(257));

        XMLWorkunit workunit = getSoapClient().getEpWorkunit().getWmSave().save(xmlRequestSaveWorkunit);

        Assertions.assertNotNull(workunit.getErrorreport());
        Assertions.assertNull(workunit.getId());
        Assertions.assertNull(workunit.getName());
        Assertions.assertEquals("name size must be between 0 and 256", workunit.getErrorreport());
    }
}
